config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
  resources :comments
  end
  resources :users 

  resources :orders, only: [:index, :show, :create, :destroy]  
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

 

  post 'payments/create'

   root to: 'static_pages#index'
 

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

	validates :name, presence: true, uniqueness: {case_sensitive: false}

	def average_rating
	  comments.average(:rating).to_f
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("lower(name) LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.order("created_at DESC").page(params[:page]).per_page(5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count       = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"products/all-#{count}-#{max_updated_at}"
	end
end

app/views/products/_comments.html.erb
<div class="product-reviews container-fluid">
	<% @comments.each do |comment| %>
	  <div class="row">
	  	<hr>
	  	<p>
	  	  <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
	  	  <% if signed_in? && current_user.admin? %>
              <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
	  	</p>
	  	  <div class="rated" data-score="<%= comment.rating %>"></div>
	  	  <p><%= comment.body %></p>
	  </div>
	<% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class ="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote:  true) do |f| %>
  <p>
  	<%= f.label :body, "Comments" %><br>
  	<%= f.text_area :body, class: "form-control" %>
  </p>
  <p>
  	<div class ="rating"></div>
  </p>
  <p>
  	<%= f.submit "Submit" %>
  </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
 
    <div class= "container-fluid col-sm-6 col-md-6" style="padding-left: 0px; padding-right: 0px;">
      <% cache product do %>
      <tr>
        <td><%= product.name %></td>
        
        <td><%= link_to image_tag(product.image_url, class: "img-responsive"), product %></td>
        <td><%= product.description %></td>
        <td><%= product.color %></td>
        <td><%= product.price %></td>
        <!--<td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
          <% end %>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class= "container">
  
  <div class="container">
    <p id="notice"><%= notice %></p>
  </div>

  <h1 class= "text-center">Our Bikes!</h1>
  
  <div class= "row">
    <% cache(cache_key_for_products) do%>
      <%= render @products %>
    <% end %>
  </div>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <p>
    <strong class="sr-only">Name:</strong>
    <% cache @product do %>
    <%= @product.name %>
    <% end %>
  </p>

  <p class="thumbnail">
    <strong class="sr-only" >Image url:</strong>
    <%= image_tag(@product.image_url, width: "500", class: "img-zoom", data_zoom_image: @product.image_url) %>
  </p>

  <p>
    <strong class="sr-only">Description:</strong>
    <span class="glyphicon glyphicon-hand-right" id="descriptionhand"></span>
    <% cache @product do %>
    <%= @product.description %>
    <% end %>
  </p>



  <p>
	  <strong>Color:</strong>
	  <%= @product.color %>
  </p>
  <p>
	  <strong>Price:</strong>
	  <%= @product.price %>
  </p>
  
  <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>
  
  <%= form_tag "/payments/create" do %>
      <%= render partial: "shared/stripe_checkout_button" %>
  
  <% end %>  

  </div>
<div class="container">


 <!-- <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>

  <%= render 'new_comment' %>
  <%= render 'comments' %> -->
    
    <div class="container">
      <%= will_paginate @comments, container: false %>
    </div>
</div>